src/Entity/Lots.php
<?php

namespace App\Entity;

use App\Repository\LotsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiSubresource;
use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\RangeFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Core\Serializer\Filter\PropertyFilter;
/**
 * @ORM\Entity(repositoryClass=LotsRepository::class)
 */
class Lots
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Fournisseurs::class, inversedBy="lots")
     * @ORM\JoinColumn(nullable=false)
     */
    private $fournisseur;

    /**
     * @ORM\OneToMany(targetEntity=Materiels::class, mappedBy="lots")
     * @ORM\JoinColumn(nullable=true)
     */
    private $materiels;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $etat;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateDebut;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateFin;

    public function __construct()
    {
        $this->materiels = new ArrayCollection();
    }

    public function __toString()
    {
        return strval($this->getId());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFournisseur(): ?Fournisseurs
    {
        return $this->fournisseur;
    }

    public function setFournisseur(?Fournisseurs $fournisseur): self
    {
        $this->fournisseur = $fournisseur;

        return $this;
    }

    /**
     * @return Collection|Materiels[]
     */
    public function getMateriels(): Collection
    {
        return $this->materiels;
    }

    public function addMateriel(Materiels $materiel): self
    {
        if (!$this->materiels->contains($materiel)) {
            $this->materiels[] = $materiel;
            $materiel->setLots($this);
        }

        return $this;
    }

    public function removeMateriel(Materiels $materiel): self
    {
        if ($this->materiels->contains($materiel)) {
            $this->materiels->removeElement($materiel);
            // set the owning side to null (unless already changed)
            if ($materiel->getLots() === $this) {
                $materiel->setLots(null);
            }
        }

        return $this;
    }

    public function getEtat(): ?bool
    {
        return $this->etat;
    }

    public function setEtat(?bool $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(?\DateTimeInterface $dateDebut): self
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(?\DateTimeInterface $dateFin): self
    {
        $this->dateFin = $dateFin;

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiSubresource;
use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\RangeFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Core\Serializer\Filter\PropertyFilter;
/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 * @ApiResource()
 */
class Users implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $passwordFirst;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $civil;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $telPortable;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $tauxHoraire;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToOne(targetEntity=Fournisseurs::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private $fournisseurs;

    /**
     * @ORM\OneToMany(targetEntity=TestsProcess::class, mappedBy="User")
     */
    private $testsProcesses;

    public function __construct()
    {
        $this->testsProcesses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPasswordFirst(): ?string
    {
        return $this->passwordFirst;
    }

    public function setPasswordFirst(?string $passwordFirst): self
    {
        $this->passwordFirst = $passwordFirst;

        return $this;
    }

    public function getCivil(): ?string
    {
        return $this->civil;
    }

    public function setCivil(string $civil): self
    {
        $this->civil = $civil;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getTelPortable(): ?string
    {
        return $this->telPortable;
    }

    public function setTelPortable(?string $telPortable): self
    {
        $this->telPortable = $telPortable;

        return $this;
    }

    public function getTauxHoraire(): ?float
    {
        return $this->tauxHoraire;
    }

    public function setTauxHoraire(?float $tauxHoraire): self
    {
        $this->tauxHoraire = $tauxHoraire;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getFournisseurs(): ?Fournisseurs
    {
        return $this->fournisseurs;
    }

    public function setFournisseurs(Fournisseurs $fournisseurs): self
    {
        $this->fournisseurs = $fournisseurs;

        // set the owning side of the relation if necessary
        if ($fournisseurs->getUser() !== $this) {
            $fournisseurs->setUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|TestsProcess[]
     */
    public function getTestsProcesses(): Collection
    {
        return $this->testsProcesses;
    }

    public function addTestsProcess(TestsProcess $testsProcess): self
    {
        if (!$this->testsProcesses->contains($testsProcess)) {
            $this->testsProcesses[] = $testsProcess;
            $testsProcess->setUser($this);
        }

        return $this;
    }

    public function removeTestsProcess(TestsProcess $testsProcess): self
    {
        if ($this->testsProcesses->contains($testsProcess)) {
            $this->testsProcesses->removeElement($testsProcess);
            // set the owning side to null (unless already changed)
            if ($testsProcess->getUser() === $this) {
                $testsProcess->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/LotsType.php
<?php

namespace App\Form;

use App\Entity\Fournisseurs;
use App\Entity\Lots;
use App\Entity\Users;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LotsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('fournisseur', EntityType::class,[
                'label' => 'Selectionnez le fournisseur',
                'class' => Fournisseurs::class,
                'multiple'=>false,
                'expanded' => false,
                'choice_label' => function ($user) {
                    return $user->getLibelle();
                }
            ])
            ->add('etat', null, ['label' => 'Lot cloturé'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Lots::class,
        ]);
    }
}

src/Controller/LotsController.php
<?php

namespace App\Controller;

use App\Entity\Lots;
use App\Form\LotsType;
use App\Repository\LotsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bridge\Twig\Mime\NotificationEmail;

/**
 * @Route("/backoffice/lots")
 */
class LotsController extends AbstractController
{
    /**
     * @Route("/", name="lots_index", methods={"GET"})
     */
    public function index(LotsRepository $lotsRepository): Response
    {
        return $this->render('lots/index.html.twig', [
            'lots' => $lotsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="lots_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $lot = new Lots();
        $lot->setDateDebut(new \DateTime());
        $form = $this->createForm(LotsType::class, $lot);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($lot);
            $entityManager->flush();
            return $this->redirectToRoute('lots_index');
        }

        return $this->render('lots/new.html.twig', [
            'lot' => $lot,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="lots_show", methods={"GET"})
     */
    public function show(Lots $lot): Response
    {


        return $this->render('lots/show.html.twig', [
            'lot' => $lot,

        ]);
    }

    /**
     * @Route("/etiquette/{id}", name="lots_show_etiquette", methods={"GET"})
     */
    public function etiquette(Lots $lot): Response
    {


        return $this->render('lots/etiquette.html.twig', [
            'lot' => $lot,

        ]);
    }

    /**
     * @Route("/{id}/edit", name="lots_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Lots $lot): Response
    {
        $form = $this->createForm(LotsType::class, $lot);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('lots_index');
        }

        return $this->render('lots/edit.html.twig', [
            'lot' => $lot,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="lots_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Lots $lot): Response
    {
        if ($this->isCsrfTokenValid('delete'.$lot->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($lot);
            $entityManager->flush();
        }

        return $this->redirectToRoute('lots_index');
    }
}

templates/lots/_delete_form.html.twig
<form method="post" action="{{ path('lots_delete', {'id': lot.id}) }}" onsubmit="return confirm('Etes vous sure de vouloir supprimer ce lot?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ lot.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/lots/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success w-100">{{ button_label|default('Enregistrer le nouveau lot dans la base de donnée') }}</button>
{{ form_end(form) }}

templates/lots/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Lots{% endblock %}

{% block body %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Lots: Fiche lot <b>{{ lot.id }}</b></h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{  path('dashbord') }}">Accueil</a></li>
                        <li class="breadcrumb-item"><a href="{{  path('lots_index') }}">Lots</a></li>
                        <li class="breadcrumb-item active">Fiche lot</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Détail du Lot <b>{{ lot.id }}</b></h3>
                            <span class="float-right">{{ include('lots/_delete_form.html.twig') }}</span>
                            <a href="{{ path('lots_edit', {'id': lot.id}) }}" class="btn btn-outline-warning float-right mr-2">Modifier</a>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body h-100">
                            <h1>Edit Lots</h1>
                            {{ form_start(form) }}
                            {{ form_row(form.fournisseur) }}
                            {{ form_widget(form.etat) }}

                            <button class="btn btn-success w-100 mt-3">{{ button_label|default('Enregistrer le nouveau lot dans la base de donnée') }}</button>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

templates/lots/etiquette.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lots{% endblock %}

{% block body %}

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Lots: Fiche lot <b>{{ lot.id }}</b></h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{  path('dashbord') }}">Accueil</a></li>
                            <li class="breadcrumb-item"><a href="{{  path('lots_index') }}">Lots</a></li>
                            <li class="breadcrumb-item active">Etiquette lot</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content-header -->
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <!-- /.card-header -->
                            <div class="card-body h-100 text-center">
                                <table class="w-100">
                                    <tr>
                                        <td style="font-size: 10em">Lot N° {{ lot.id  }}</td>
                                    </tr>
                                    <tr>
                                        <td style="font-size: 5em">{{ lot.fournisseur.libelle }}</td>
                                    </tr>
                                    <tr>
                                        <td style="font-size: 5em"><small>Date de Création: </small> {{ lot.dateDebut|date("m/d/Y") }}</td>
                                    </tr>
                                    <tr>
                                        <td style="font-size: 5em">{{ lot.fournisseur.user.email }}</td>
                                    </tr>
                                    <tr>
                                        <td style="font-size: 5em">{{lot.fournisseur.user.civil~' '~ lot.fournisseur.user.nom ~ ' '~lot.fournisseur.user.prenom }}</td>
                                    </tr>
                                    <tr>
                                        <td style="font-size: 5em">{{lot.fournisseur.telPortable }}</td>
                                    </tr>
                                    <tr>
                                        <td style="font-size: 5em">{{lot.fournisseur.telFixe }}</td>
                                    </tr>
                                    <tr>
                                        <td style="font-size: 10em">Lot N° {{ lot.id  }}</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </section>
    </div>
{% endblock %}

{% block javascripts %}

    <!-- DataTables -->
    <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('js/adminlte.min.js') }}"></script>
    <!-- page script -->
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true,
                "autoWidth": false,
            });
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
{% endblock %}

templates/lots/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Lots{% endblock %}
{% block body %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Lots</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{  path('dashbord') }}">Accueil</a></li>
                            <li class="breadcrumb-item active">Lots</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Tableau des lots</h3>
                                <a href="{{ path('lots_new') }}" class="btn btn-outline-success float-right">Entrer un nouveau lot</a>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Fournisseur</th>
                                        <th>Nb</th>
                                        <th>Etat</th>
                                        <th>actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for lot in lots %}
                                        <tr>
                                            <td>{{ lot.id }}</td>
                                            <td>{{ lot.fournisseur.libelle }}</td>
                                            {% if  lot.etat == true %}
                                                <td><span class="badge badge-success">{{ lot.materiels|length }} appareil(s)</span> </td>
                                            {% else %}
                                                <td><span class="badge badge-warning">{{ lot.materiels|length }} appareil(s)</span> </td>
                                            {% endif %}
                                            <td>
                                                {% if  lot.etat == true %}
                                                <span class="badge badge-success">Fermé</span>
                                                {% else %}
                                                <span class="badge badge-warning">Ouvert</span>
                                                {% endif %}
                                            </td>
                                            <td>
                                                <a href="{{ path('lots_show', {'id': lot.id}) }}" class="btn btn-success">Voir</a>
                                                <a href="{{ path('lots_edit', {'id': lot.id}) }}" class="btn btn-warning">Modif.</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th>Id</th>
                                        <th>Fournisseur</th>
                                        <th>Nb</th>
                                        <th>Etat</th>
                                        <th>actions</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
{% endblock %}
{% block javascripts %}

    <!-- DataTables -->
    <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('js/adminlte.min.js') }}"></script>
    <!-- page script -->
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true,
                "autoWidth": false,
            });
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
{% endblock %}

templates/lots/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Lot{% endblock %}

{% block body %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Marques : Entrée d'un Lot</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{  path('dashbord') }}">Accueil</a></li>
                            <li class="breadcrumb-item"><a href="{{  path('lots_index') }}">Lots</a></li>
                            <li class="breadcrumb-item active">Entrée d'un lot en BDD</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="card card-default">
                    <div class="card-header">
                        <h3 class="card-title">Formulaire d'entrée d'un lot</h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        {{ form_start(form) }}
                        {{ form_row(form.fournisseur) }}
                        <div style="display: none">
                        {{ form_row(form.etat) }}
                        </div>
                        <button class="btn btn-success w-100">{{ button_label|default('Enregistrer le nouveau lot dans la base de donnée') }}</button>
                        {{ form_end(form) }}

                    </div>
                </div>
            </div>
        </section>
    </div>


{% endblock %}